@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

TutorMap *-right-> "1" UniquePersonList
TutorMap *-right-> "1" UniqueLabelList
UniqueLabelList -[hidden]down- UniquePersonList
UniqueLabelList -[hidden]down- UniquePersonList

UniqueLabelList -right-> "*" Label
UniquePersonList -right-> Person

Person -up-> "*" Label

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> "*" Subject
Person *--> "*" Relation
@enduml
