@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "TutorMap Storage" #F4F6F6{
Class "<<interface>>\nTutorMapStorage" as TutorMapStorage
Class JsonTutorMapStorage
Class JsonSerializableTutorMap
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" TutorMapStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> TutorMapStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonTutorMapStorage .up.|> TutorMapStorage
JsonTutorMapStorage ..> JsonSerializableTutorMap
JsonSerializableTutorMap --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
