@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":TutorMapParser" as abp LOGIC_COLOR
Participant ":Parser Classes" as ecp LOGIC_COLOR
Participant "command:Command" as ec LOGIC_COLOR

[-> logic : execute
activate logic
logic -> abp ++: parseCommand(commandText)
create ecp
abp --> ecp ++
ecp --> abp --
abp -> ecp ++: parse(arguments)
create ec
ecp -> ec ++: Command(parsed arguments)
ec --> ecp --
ecp --> abp --: command
abp --> logic --: command
<-- logic: command.execute()
@enduml
